import Head from 'next/head'
import styles from '../styles/Home.module.css'
import HomeBlock from "../components/HomeBlock";
import {supabase} from "../components/supabase";

export default function Home() {
	return (
		<div className={styles.container}>
			<Head>
				<title>SpleefX</title>
				<meta name="description" content="Generated by create next app"/>
				<link rel="icon" href="/favicon.ico"/>
			</Head>

			<main className={styles.main}>
				<h1 className={styles.title}>SpleefX</h1>

				<p className={styles.description}>
					An advanced, powerful, customizable engine for spleef-like games
				</p>
				<div className={styles.grid}>
					<HomeBlock name="Wiki"
										 description="Find in-depth guides about SpleefX"
										 link="https://github.com/SpleefX/SpleefX/wiki"
					/>
					<HomeBlock name="Try"
										 description="Bring over your friends and try the plugin out"
										 link="/try"
					/>
					<HomeBlock name="Support"
										 description="Join the Discord server for quick support"
										 link="https://discord.gg/uwf72ZN"
					/>
					<HomeBlock name="Get"
										 description="Get the plugin from SpigotMC"
										 link="https://www.spigotmc.org/resources/73093/"
					/>
				</div>
			</main>
		</div>
	)
}
